### ISSUE TITLE
Deploy application

### ISSUE THREAD

**Issue by shreyakurian02** [shreyakurian02/neeto-ui-challenge#8]
Deployed application URL : https://neeto-ui-challenge-shreya.neetoreviewapp.net/

**Credentials**:

Username: oliver@example.com
Password: welcome

@yedhink @navaneethsdk Please review

**Comment by yedhink** [comment]
LGTM.

**Comment by navaneethsdk** [comment]
@shreyakurian02 A few comments:
- [x] Let's stick to `event` instead of `e`. https://github.com/shreyakurian02/neeto-ui-challenge/blob/a597b483d81ce97fde21e8c33139e4e94b9bab33/app/javascript/src/components/Dashboard/Contacts/index.jsx#L64
- [x] Let's move this to a separate utils function prefixed with `render` keyword. Please correct all occurrences [Refer](https://academy.bigbinary.com/learn-react/react-best-practices/naming-conventions-in-react#when-to-use-the-render-keyword): https://github.com/shreyakurian02/neeto-ui-challenge/blob/a597b483d81ce97fde21e8c33139e4e94b9bab33/app/javascript/src/components/Dashboard/Contacts/utils.jsx#L18-L27 https://github.com/shreyakurian02/neeto-ui-challenge/blob/a597b483d81ce97fde21e8c33139e4e94b9bab33/app/javascript/src/components/Dashboard/Contacts/utils.jsx#L44-L52
- [x] Let's add one validation to check if the title has at least one alphanumeric character https://github.com/shreyakurian02/neeto-ui-challenge/blob/a597b483d81ce97fde21e8c33139e4e94b9bab33/app/javascript/src/components/Dashboard/Notes/constants.js#L14-L16

Rest of the app LGTM.
